"""create phase 5 reminder and notification tables

Revision ID: ca9da7f0d454
Revises: a808a053b916
Create Date: 2026-09-27 17:26:05.929237+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca9da7f0d454'
down_revision: Union[str, None] = 'a808a053b916'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('reminder_type', sa.Enum('medication', 'appointment', name='reminder_type'), nullable=False),
    sa.Column('medication_id', sa.UUID(), nullable=True),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('local_time', sa.Time(), nullable=True),
    sa.Column('recurrence', sa.Enum('none', 'daily', 'weekly', name='reminder_recurrence'), nullable=False),
    sa.Column('recurrence_interval', sa.Integer(), nullable=False),
    sa.Column('frequency_text', sa.String(length=100), nullable=True),
    sa.Column('appointment_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lead_time_minutes', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('next_occurrence_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('active', 'paused', 'completed', 'cancelled', name='reminder_status'), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('review_reason', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reminders_appointment_id', 'reminders', ['appointment_id'], unique=False)
    op.create_index('ix_reminders_medication_id', 'reminders', ['medication_id'], unique=False)
    op.create_index('ix_reminders_patient_id', 'reminders', ['patient_id'], unique=False)
    op.create_index('ix_reminders_status_next_occurrence', 'reminders', ['status', 'next_occurrence_at'], unique=False)
    op.create_index('uq_reminders_medication_slot', 'reminders', ['medication_id', 'local_time'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('reminder_id', sa.UUID(), nullable=True),
    sa.Column('notification_type', sa.Enum('medication_reminder', 'appointment_reminder', name='notification_type'), nullable=False),
    sa.Column('medication_id', sa.UUID(), nullable=True),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sending', 'sent', 'failed', 'skipped', name='notification_status'), nullable=False),
    sa.Column('channel', sa.Enum('console', 'whatsapp', name='delivery_channel'), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reminder_id'], ['reminders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_patient_id', 'notifications', ['patient_id'], unique=False)
    op.create_index('ix_notifications_patient_id_created_at', 'notifications', ['patient_id', 'created_at'], unique=False)
    op.create_index('ix_notifications_reminder_id', 'notifications', ['reminder_id'], unique=False)
    op.create_index('ix_notifications_status_scheduled_for', 'notifications', ['status', 'scheduled_for'], unique=False)
    op.create_index('uq_notifications_idempotency_key', 'notifications', ['idempotency_key'], unique=True)
    op.add_column('patients', sa.Column('timezone', sa.String(length=64), server_default='UTC', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'timezone')
    op.drop_index('uq_notifications_idempotency_key', table_name='notifications')
    op.drop_index('ix_notifications_status_scheduled_for', table_name='notifications')
    op.drop_index('ix_notifications_reminder_id', table_name='notifications')
    op.drop_index('ix_notifications_patient_id_created_at', table_name='notifications')
    op.drop_index('ix_notifications_patient_id', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('uq_reminders_medication_slot', table_name='reminders')
    op.drop_index('ix_reminders_status_next_occurrence', table_name='reminders')
    op.drop_index('ix_reminders_patient_id', table_name='reminders')
    op.drop_index('ix_reminders_medication_id', table_name='reminders')
    op.drop_index('ix_reminders_appointment_id', table_name='reminders')
    op.drop_table('reminders')
    # ### end Alembic commands ###
    # Postgres keeps a named enum type alive after its table is dropped, so a
    # repeated upgrade/downgrade cycle would fail on CREATE TYPE.  Dropped
    # explicitly, matching the Phase 2 migration's convention.
    op.execute("DROP TYPE IF EXISTS delivery_channel")
    op.execute("DROP TYPE IF EXISTS notification_status")
    op.execute("DROP TYPE IF EXISTS notification_type")
    op.execute("DROP TYPE IF EXISTS reminder_recurrence")
    op.execute("DROP TYPE IF EXISTS reminder_status")
    op.execute("DROP TYPE IF EXISTS reminder_type")
