"""create phase 2 discharge document and extraction run tables

Revision ID: a808a053b916
Revises: dc558334188b
Create Date: 2026-09-25 17:29:10.165587+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a808a053b916'
down_revision: Union[str, None] = 'dc558334188b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discharge_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('document_type', sa.Enum('discharge_summary', 'medication_list', 'lab_report', 'other', name='discharge_document_type'), nullable=False),
    sa.Column('processing_status', sa.Enum('pending', 'processing', 'completed', 'failed', name='discharge_document_processing_status'), nullable=False),
    sa.Column('ocr_status', sa.Enum('not_required', 'completed', 'failed', 'skipped', name='discharge_document_ocr_status'), nullable=False),
    sa.Column('extraction_status', sa.Enum('pending', 'completed', 'needs_review', 'failed', name='discharge_document_extraction_status'), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_discharge_documents_created_at', 'discharge_documents', ['created_at'], unique=False)
    op.create_index('ix_discharge_documents_patient_id', 'discharge_documents', ['patient_id'], unique=False)
    op.create_index('ix_discharge_documents_processing_status', 'discharge_documents', ['processing_status'], unique=False)
    op.create_index('uq_discharge_documents_patient_hash', 'discharge_documents', ['patient_id', 'sha256_hash'], unique=True)
    op.create_table('extraction_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('started', 'completed', 'failed', name='extraction_run_status'), nullable=False),
    sa.Column('raw_ocr_character_count', sa.Integer(), nullable=True),
    sa.Column('extraction_error', sa.Text(), nullable=True),
    sa.Column('validation_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['discharge_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_extraction_runs_document_id', 'extraction_runs', ['document_id'], unique=False)
    op.create_index('ix_extraction_runs_started_at', 'extraction_runs', ['started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_extraction_runs_started_at', table_name='extraction_runs')
    op.drop_index('ix_extraction_runs_document_id', table_name='extraction_runs')
    op.drop_table('extraction_runs')
    op.drop_index('uq_discharge_documents_patient_hash', table_name='discharge_documents')
    op.drop_index('ix_discharge_documents_processing_status', table_name='discharge_documents')
    op.drop_index('ix_discharge_documents_patient_id', table_name='discharge_documents')
    op.drop_index('ix_discharge_documents_created_at', table_name='discharge_documents')
    op.drop_table('discharge_documents')
    # ### end Alembic commands ###

    # PostgreSQL keeps enum types as standalone database objects, so they
    # must be dropped explicitly.  Without this a downgrade/upgrade cycle
    # would fail with "type already exists".
    op.execute("DROP TYPE IF EXISTS extraction_run_status")
    op.execute("DROP TYPE IF EXISTS discharge_document_type")
    op.execute("DROP TYPE IF EXISTS discharge_document_processing_status")
    op.execute("DROP TYPE IF EXISTS discharge_document_ocr_status")
    op.execute("DROP TYPE IF EXISTS discharge_document_extraction_status")
