"""create_phase_1_tables

Revision ID: dc558334188b
Revises: 
Create Date: 2026-09-25 12:01:51.287204+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc558334188b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_number', sa.String(length=50), nullable=False),
    sa.Column('caregiver_contact', sa.String(length=50), nullable=True),
    sa.Column('discharge_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_name', sa.String(length=255), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'completed', 'cancelled', 'missed', name='appointment_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_appointments_date', 'appointments', ['date'], unique=False)
    op.create_index('ix_appointments_patient_id', 'appointments', ['patient_id'], unique=False)
    op.create_table('checkins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('flag_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_checkins_date', 'checkins', ['date'], unique=False)
    op.create_index('ix_checkins_patient_id', 'checkins', ['patient_id'], unique=False)
    op.create_table('medications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=False),
    sa.Column('frequency', sa.String(length=100), nullable=False),
    sa.Column('timing', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_medications_patient_id', 'medications', ['patient_id'], unique=False)
    op.create_table('warning_symptoms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='symptom_severity'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_warning_symptoms_patient_id', 'warning_symptoms', ['patient_id'], unique=False)
    op.create_table('adherence_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('medication_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('taken', sa.Boolean(), nullable=False),
    sa.Column('taken_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_adherence_logs_medication_id', 'adherence_logs', ['medication_id'], unique=False)
    op.create_index('ix_adherence_logs_patient_id', 'adherence_logs', ['patient_id'], unique=False)
    op.create_index('ix_adherence_logs_scheduled_time', 'adherence_logs', ['scheduled_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_adherence_logs_scheduled_time', table_name='adherence_logs')
    op.drop_index('ix_adherence_logs_patient_id', table_name='adherence_logs')
    op.drop_index('ix_adherence_logs_medication_id', table_name='adherence_logs')
    op.drop_table('adherence_logs')
    op.drop_index('ix_warning_symptoms_patient_id', table_name='warning_symptoms')
    op.drop_table('warning_symptoms')
    op.drop_index('ix_medications_patient_id', table_name='medications')
    op.drop_table('medications')
    op.drop_index('ix_checkins_patient_id', table_name='checkins')
    op.drop_index('ix_checkins_date', table_name='checkins')
    op.drop_table('checkins')
    op.drop_index('ix_appointments_patient_id', table_name='appointments')
    op.drop_index('ix_appointments_date', table_name='appointments')
    op.drop_table('appointments')
    op.drop_table('patients')
    # ### end Alembic commands ###
